import {
  Sparkles,
  PenLine,
  Code2,
  Image,
  Languages,
  FileText,
  Lightbulb,
  Search,
  MessageCircle,
  BarChart3,
  Wand2,
  Gift,
  ShoppingBag,
  GraduationCap,
  TrendingUp,
  Car,
  Wallet,
  Brain,
  PlaneIcon,
  PackageIcon,
  CoinsIcon,
  CalendarCheck,
  ReceiptTextIcon,
} from "lucide-react";

export const AI_STARTER = [
  {
    title: "برام یک سفر برنامه‌ریزی کن",
    description: "مقصد، بودجه و زمان سفرت رو بگو",
    icon: PlaneIcon,
    color: "bg-sky-500/15",
    iconColor: "text-sky-400",
  },
  {
    title: "چی بخرم؟",
    description: "محصول مناسب رو با توجه به بودجه‌ات پیدا کن",
    icon: ShoppingBag,
    color: "bg-violet-500/15",
    iconColor: "text-violet-400",
  },
  {
    title: "هزینه ارسال رو حساب کن",
    description: "مبدأ، مقصد و مشخصات بسته رو وارد کن",
    icon: PackageIcon,
    color: "bg-amber-500/15",
    iconColor: "text-amber-400",
  },
  {
    title: "وضعیت طلای امروز چطوره؟",
    description: "قیمت و روند بازار طلا رو بررسی کن",
    icon: CoinsIcon,
    color: "bg-yellow-500/15",
    iconColor: "text-yellow-400",
  },
  {
    title: "یک متن حرفه‌ای بنویس",
    description: "ایمیل، پیام، کپشن یا متن کاری",
    icon: PenLine,
    color: "bg-blue-500/15",
    iconColor: "text-blue-400",
  },
  {
    title: "کارهای امروزمو مرتب کن",
    description: "برنامه روزانه‌ات رو سریع بچین",
    icon: CalendarCheck,
    color: "bg-emerald-500/15",
    iconColor: "text-emerald-400",
  },
  {
    title: "دنبال یک محصول بگرد",
    description: "قیمت و گزینه‌های مناسب رو مقایسه کن",
    icon: Search,
    color: "bg-cyan-500/15",
    iconColor: "text-cyan-400",
  },
  {
    title: "این هزینه‌ها رو بررسی کن",
    description: "جمع، دسته‌بندی و تحلیل هزینه‌ها",
    icon: ReceiptTextIcon,
    color: "bg-orange-500/15",
    iconColor: "text-orange-400",
  },
];

export const AI_CATEGORIES = [
  {
    id: "write",
    title: "نوشتن",
    icon: PenLine,
    color: "bg-blue-500/15",
    iconColor: "text-blue-400",
  },
  {
    id: "code",
    title: "کدنویسی",
    icon: Code2,
    color: "bg-violet-500/15",
    iconColor: "text-violet-400",
  },
  {
    id: "image",
    title: "تصویر",
    icon: Image,
    color: "bg-pink-500/15",
    iconColor: "text-pink-400",
  },
  {
    id: "translate",
    title: "ترجمه",
    icon: Languages,
    color: "bg-sky-500/15",
    iconColor: "text-sky-400",
  },
  {
    id: "summarize",
    title: "خلاصه‌سازی",
    icon: FileText,
    color: "bg-amber-500/15",
    iconColor: "text-amber-400",
  },
  {
    id: "ideas",
    title: "ایده‌پردازی",
    icon: Lightbulb,
    color: "bg-yellow-500/15",
    iconColor: "text-yellow-400",
  },
  {
    id: "search",
    title: "جستجو",
    icon: Search,
    color: "bg-cyan-500/15",
    iconColor: "text-cyan-400",
  },
  {
    id: "chat",
    title: "گفتگو",
    icon: MessageCircle,
    color: "bg-emerald-500/15",
    iconColor: "text-emerald-400",
  },
  {
    id: "analyze",
    title: "تحلیل",
    icon: BarChart3,
    color: "bg-orange-500/15",
    iconColor: "text-orange-400",
  },
  {
    id: "creative",
    title: "خلاقیت",
    icon: Wand2,
    color: "bg-fuchsia-500/15",
    iconColor: "text-fuchsia-400",
  },
  {
    id: "learn",
    title: "یادگیری",
    icon: GraduationCap,
    color: "bg-indigo-500/15",
    iconColor: "text-indigo-400",
  },
  {
    id: "more",
    title: "بیشتر",
    icon: Sparkles,
    color: "bg-zinc-700/60",
    iconColor: "text-zinc-300",
  },
];
