import {
  Car,
  ShoppingBag,
  Package,
  Wallet,
  Coins,
  Plane,
  Store,
  Cpu,
  Home,
  History,
  LayoutGrid,
  User,
  QrCode,
  ArrowUpRight,
  ArrowDownLeft,
  Phone,
  Receipt,
  Zap,
  MapPin,
  Gift,
  Percent,
} from 'lucide-react'
import type { QuickAction, Service, PromoCard, Transaction, BottomNavItem } from './types'

export const QUICK_ACTIONS: QuickAction[] = [
  { id: 'pay', label: 'پرداخت', icon: QrCode, href: '/app/pay' },
  { id: 'send', label: 'انتقال', icon: ArrowUpRight, href: '/app/transfer' },
  { id: 'receive', label: 'دریافت', icon: ArrowDownLeft, href: '/app/receive' },
  { id: 'topup', label: 'شارژ', icon: Phone, href: '/app/topup' },
  { id: 'bill', label: 'قبض', icon: Receipt, href: '/app/bill' },
  { id: 'charge', label: 'کارت به کارت', icon: Zap, href: '/app/card2card' },
]

export const SERVICES: Service[] = [
  {
    id: 'trip',
    label: 'تریپ',
    icon: Car,
    color: 'bg-blue-500/15',
    iconColor: 'text-blue-400',
    badge: undefined,
  },
  {
    id: 'shopex',
    label: 'شاپکس',
    icon: ShoppingBag,
    color: 'bg-violet-500/15',
    iconColor: 'text-violet-400',
    badge: undefined,
  },
  {
    id: 'postex',
    label: 'پستکس',
    icon: Package,
    color: 'bg-amber-500/15',
    iconColor: 'text-amber-400',
    badge: '۳',
  },
  {
    id: 'gold',
    label: 'دات گلد',
    icon: Coins,
    color: 'bg-yellow-500/15',
    iconColor: 'text-yellow-400',
    badge: undefined,
  },
  {
    id: 'airlines',
    label: 'ایرلاینز',
    icon: Plane,
    color: 'bg-sky-500/15',
    iconColor: 'text-sky-400',
    badge: undefined,
  },
  {
    id: 'sell',
    label: 'دات سل',
    icon: Store,
    color: 'bg-emerald-500/15',
    iconColor: 'text-emerald-400',
    isNew: true,
  },
  {
    id: 'mydot',
    label: 'مای دات',
    icon: Cpu,
    color: 'bg-zinc-700/60',
    iconColor: 'text-zinc-300',
    badge: undefined,
  },
  {
    id: 'more',
    label: 'بیشتر',
    icon: LayoutGrid,
    color: 'bg-zinc-700/60',
    iconColor: 'text-zinc-300',
    badge: undefined,
  },
]

export const PROMO_CARDS: PromoCard[] = [
  {
    id: 'cashback',
    title: '۲۰٪ کش‌بک',
    subtitle: 'برای اولین سفر با دات تریپ این هفته',
    cta: 'استفاده از پیشنهاد',
    accentColor: 'text-blue-400',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/20',
  },
  {
    id: 'gold',
    title: 'طلا بخر، جایزه بگیر',
    subtitle: 'خرید بالای ۵۰۰ هزار تومان = ۱ گرم هدیه',
    cta: 'سرمایه‌گذاری',
    accentColor: 'text-yellow-400',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/20',
  },
  {
    id: 'postex',
    title: 'ارسال رایگان',
    subtitle: 'برای سفارش‌های بالای ۳۰۰ هزار تومان',
    cta: 'خرید از شاپکس',
    accentColor: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/20',
  },
]

export const TRANSACTIONS: Transaction[] = [
  {
    id: 'tx1',
    title: 'دات تریپ',
    subtitle: 'سفر از تجریش به ونک',
    amount: '‎−۸۵,۰۰۰',
    type: 'debit',
    icon: Car,
    iconBg: 'bg-blue-500/15',
    date: 'امروز، ۱۴:۳۲',
  },
  {
    id: 'tx2',
    title: 'شارژ کیف پول',
    subtitle: 'از کارت ملت *۴۳۲۱',
    amount: '‎+۲,۰۰۰,۰۰۰',
    type: 'credit',
    icon: Wallet,
    iconBg: 'bg-emerald-500/15',
    date: 'امروز، ۱۱:۰۵',
  },
  {
    id: 'tx3',
    title: 'شاپکس',
    subtitle: 'خرید: ایرپاد پرو',
    amount: '‎−۴,۸۵۰,۰۰۰',
    type: 'debit',
    icon: ShoppingBag,
    iconBg: 'bg-violet-500/15',
    date: 'دیروز، ۱۹:۱۵',
  },
  {
    id: 'tx4',
    title: 'قبض برق',
    subtitle: 'پرداخت خودکار',
    amount: '‎−۱۲۴,۰۰۰',
    type: 'debit',
    icon: Zap,
    iconBg: 'bg-amber-500/15',
    date: 'دیروز، ۰۸:۰۰',
  },
  {
    id: 'tx5',
    title: 'دات گلد',
    subtitle: 'فروش ۲ گرم طلا',
    amount: '‎+۱,۶۴۰,۰۰۰',
    type: 'credit',
    icon: Coins,
    iconBg: 'bg-yellow-500/15',
    date: '۱۴۰۳/۰۴/۲۸',
  },
]

export const BOTTOM_NAV: BottomNavItem[] = [
  { id: 'home', label: 'خانه', icon: Home, href: '/app', isActive: true },
  { id: 'explore', label: 'اکتشاف', icon: MapPin, href: '/app/explore' },
  { id: 'gifts', label: 'جوایز', icon: Gift, href: '/app/gifts' },
  { id: 'offers', label: 'پیشنهادها', icon: Percent, href: '/app/offers' },
  { id: 'profile', label: 'پروفایل', icon: User, href: '/app/profile' },
]
