import {
  Car,
  ShoppingBag,
  Package,
  Wallet,
  Coins,
  Plane,
  Store,
  Cpu,
  Home,
  LayoutGrid,
  User,
  ArrowUpRight,
  Zap,
  Gift,
  Percent,
  Wallet2,
  Sparkles,
  RefreshCw,
  ImageIcon,
  TargetIcon,
  SparklesIcon,
  BotIcon,
  Wand2Icon,
  WandSparklesIcon,
} from "lucide-react";
import type { QuickAction, Service, Transaction, BottomNavItem } from "./types";
export const QUICK_ACTIONS: QuickAction[] = [
  {
    id: "earn",
    label: "کسب درآمد",
    icon: Coins,
    href: "/earn",
  },
  {
    id: "transfer",
    label: "انتقال",
    icon: ArrowUpRight,
    href: "/wallet/transfer",
  },
  {
    id: "convert",
    label: "تبدیل",
    icon: RefreshCw,
    href: "/wallet/convert",
  },
  {
    id: "nft",
    label: "بازار NFT",
    icon: ImageIcon,
    href: "/wallet/nft-market",
  },
  {
    id: "rewards",
    label: "جوایز",
    icon: Gift,
    href: "/rewards",
  },
  {
    id: "ai",
    label: "ابزار AI",
    icon: Sparkles,
    href: "/ai",
  },
];

export const SERVICES: Service[] = [
  {
    id: "mydot",
    label: "مای دات",
    logo: "/my_dot_logo.svg",
    color: "bg-zinc-700/10",
    badge: undefined,
    href: "https://mydot.one/auth",
  },
  {
    id: "trip",
    label: "تریپ",
    icon: Car,
    color: "bg-blue-500/15",
    iconColor: "text-blue-400",
    badge: undefined,
    href: "https://trip.dotone.ir/",
  },
  {
    id: "shopex",
    label: "شاپکس",
    icon: ShoppingBag,
    color: "bg-violet-500/15",
    iconColor: "text-violet-400",
    badge: undefined,
    href: "https://shapex.ir/",
  },
  {
    id: "postex",
    label: "پستکس",
    icon: Package,
    color: "bg-amber-500/15",
    iconColor: "text-amber-400",
    badge: "۳",
    href: "https://postex.ir/",
  },
  {
    id: "gold",
    label: "دات گلد",
    icon: Coins,
    color: "bg-yellow-500/15",
    iconColor: "text-yellow-400",
    badge: undefined,
    href: "https://dotone.gold/",
  },
  {
    id: "airlines",
    label: "ایرلاینز",
    icon: Plane,
    color: "bg-sky-500/15",
    iconColor: "text-sky-400",
    badge: undefined,
    href: "https://airlines.dotone.ir/",
  },
  {
    id: "sell",
    label: "دات سل",
    icon: Store,
    color: "bg-emerald-500/15",
    iconColor: "text-emerald-400",
    isNew: true,
    href: "https://dotonecell.ir/",
  },

  {
    id: "more",
    label: "بیشتر",
    icon: LayoutGrid,
    color: "bg-zinc-700/60",
    iconColor: "text-zinc-300",
    badge: undefined,
  },
];

export const PROMO_CARDS = [
  {
    id: 3,
    title: "دات وان تریپ",
    subtitle: "رزرو سفر و تجربه‌های جدید با چند کلیک",
    cta: "شروع سفر",
    image: "/banners/dotone-trip.png",
    bg: "from-sky-600 to-blue-800",
  },
  {
    id: 4,
    title: "دات وان گلد",
    subtitle: "خرید و مدیریت طلای دیجیتال با امنیت بالا",
    cta: "مشاهده طلا",
    image: "/banners/dotone-gold.png",
    bg: "from-yellow-500 to-amber-700",
  },
  {
    id: 1,
    title: "۲۰٪ تخفیف خرید اول",
    subtitle: "با اولین سفارش خود از تخفیف ویژه استفاده کنید",
    cta: "شروع خرید",
    image: "/banners/first-order.png",
    bg: "from-blue-600 to-indigo-700",
  },
  {
    id: 2,
    title: "ارسال رایگان امروز",
    subtitle: "برای سفارش‌های بالای ۳۰۰ هزار تومان",
    cta: "مشاهده پیشنهاد",
    image: "/banners/free-shipping.png",
    bg: "from-emerald-600 to-teal-700",
  },
];
export const TRANSACTIONS: Transaction[] = [
  {
    id: "tx1",
    title: "دات تریپ",
    subtitle: "سفر از تجریش به ونک",
    amount: "‎−۸۵,۰۰۰",
    type: "debit",
    icon: Car,
    iconBg: "bg-blue-500/15",
    date: "امروز، ۱۴:۳۲",
  },
  {
    id: "tx2",
    title: "شارژ کیف پول",
    subtitle: "از کارت ملت *۴۳۲۱",
    amount: "‎+۲,۰۰۰,۰۰۰",
    type: "credit",
    icon: Wallet,
    iconBg: "bg-emerald-500/15",
    date: "امروز، ۱۱:۰۵",
  },
  {
    id: "tx3",
    title: "شاپکس",
    subtitle: "خرید: ایرپاد پرو",
    amount: "‎−۴,۸۵۰,۰۰۰",
    type: "debit",
    icon: ShoppingBag,
    iconBg: "bg-violet-500/15",
    date: "دیروز، ۱۹:۱۵",
  },
  {
    id: "tx4",
    title: "قبض برق",
    subtitle: "پرداخت خودکار",
    amount: "‎−۱۲۴,۰۰۰",
    type: "debit",
    icon: Zap,
    iconBg: "bg-amber-500/15",
    date: "دیروز، ۰۸:۰۰",
  },
  {
    id: "tx5",
    title: "دات گلد",
    subtitle: "فروش ۲ گرم طلا",
    amount: "‎+۱,۶۴۰,۰۰۰",
    type: "credit",
    icon: Coins,
    iconBg: "bg-yellow-500/15",
    date: "۱۴۰۳/۰۴/۲۸",
  },
];

export const BOTTOM_NAV: BottomNavItem[] = [
  { id: "home", label: "خانه", icon: Home, href: "/app", defaultActive: true },
  { id: "wallet", label: "کیف پول", icon: Wallet2, href: "/wallet" },
  { id: "gifts", label: "جوایز", icon: Gift, href: "/app/gifts" },
  { id: "offers", label: "پیشنهادها", icon: Percent, href: "/app/offers" },
  { id: "profile", label: "پروفایل", icon: User, href: "/app/profile" },
];

export const LEFT_BOTTOM_NAV: BottomNavItem[] = [
  // { id: "home", label: "خانه", icon: Home, href: "/app", defaultActive: true },
  { id: "wallet", label: "کیف پول", icon: Wallet2, href: "/wallet" },
  { id: "profile", label: "پروفایل", icon: User, href: "/profile" },
];
export const RIGHT_BOTTOM_NAV: BottomNavItem[] = [
  {
    id: "missions",
    label: "ماموریت‌ها",
    icon: TargetIcon,
    href: "/missions",
  },
  {
    id: "ai",
    label: "هوش مصنوعی",
    icon: WandSparklesIcon,
    href: "/ai",
  },
];
